services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /data/postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ecommerce-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 5s
            timeout: 5s
            retries: 5

    mongo:
        image: mongo
        container_name: mongo-db
        ports:
            - '27017:27017'
        networks:
            - ecommerce-network
        volumes:
            - mongo-data:/data/db

    my-common:
        build:
            context: ./common
            dockerfile: Dockerfile
        volumes:
            - my-common-dist:/usr/src/app/dist # bu volume sayesinde diğer uygulamlarla paylaşabileceğiz
            - my-common-modules:/usr/src/app/node_modules

    api-gateway:
        container_name: api-gateway
        build:
            context: .
            dockerfile: ./api-gateway/dockerfile
        ports:
            - '3000:3000'
        volumes:
            # Bind mount sayesinde kodda değişiklik otomatik yüklenir
            - ./api-gateway:/usr/src/app/api-gateway
            - /usr/src/app/api-gateway/node_modules

            # ortak kütüphane buradan paylaşıma alınır
            - my-common-dist:/usr/src/app/common/dist
            - my-common-modules:/usr/src/app/common/node_modules
        networks:
            - ecommerce-network
        depends_on:
            - my-common
            - users-microservice
            - auth-microservice
            - products-microservice
            - orders-microservice

    auth-microservice:
        container_name: auth-microservice
        restart: always
        build:
            context: .
            dockerfile: ./auth-microservice/dockerfile
        volumes:
            # Bind mount sayesinde kodda değişiklik otomatik yüklenir
            - ./auth-microservice:/usr/src/app/auth-microservice
            - /usr/src/app/auth-microservice/node_modules

            # ortak kütüphane buradan paylaşıma alınır
            - my-common-dist:/usr/src/app/common/dist
            - my-common-modules:/usr/src/app/common/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy
            users-microservice:
                condition: service_started

    users-microservice:
        container_name: users-microservice
        build:
            context: .
            dockerfile: ./users-microservice/dockerfile
        volumes:
            # Bind mount sayesinde kodda değişiklik otomatik yüklenir
            - ./users-microservice:/usr/src/app/users-microservice
            - /usr/src/app/users-microservice/node_modules

            # ortak kütüphane buradan paylaşıma alınır
            - my-common-dist:/usr/src/app/common/dist
            - my-common-modules:/usr/src/app/common/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

    products-microservice:
        container_name: products-microservice
        build:
            context: .
            dockerfile: ./products-microservice/dockerfile
        volumes:
            # Bind mount sayesinde kodda değişiklik otomatik yüklenir
            - ./products-microservice:/usr/src/app/products-microservice
            - /usr/src/app/products-microservice/node_modules

            # ortak kütüphane buradan paylaşıma alınır
            - my-common-dist:/usr/src/app/common/dist
            - my-common-modules:/usr/src/app/common/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

    orders-microservice:
        container_name: orders-microservice
        build:
            context: .
            dockerfile: ./orders-microservice/dockerfile
        volumes:
            # Bind mount sayesinde kodda değişiklik otomatik yüklenir
            - ./orders-microservice:/usr/src/app/orders-microservice
            - /usr/src/app/orders-microservice/node_modules

            # ortak kütüphane buradan paylaşıma alınır
            - my-common-dist:/usr/src/app/common/dist
            - my-common-modules:/usr/src/app/common/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

    cart-microservice:
        container_name: cart-microservice
        build:
            context: .
            dockerfile: ./cart-microservice/dockerfile
        volumes:
            # Bind mount sayesinde kodda değişiklik otomatik yüklenir
            - ./cart-microservice:/usr/src/app/cart-microservice
            - /usr/src/app/cart-microservice/node_modules

            # ortak kütüphane buradan paylaşıma alınır
            - my-common-dist:/usr/src/app/common/dist
            - my-common-modules:/usr/src/app/common/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

networks:
    ecommerce-network:
        driver: bridge

volumes:
    postgres_data:
    mongo-data:
    my-common-dist:
        name: my-common-dist
    my-common-modules:
        name: my-common-modules
