services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /data/postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ecommerce-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 5s
            timeout: 5s
            retries: 5

    api-gateway:
        container_name: api-gateway
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./api-gateway:/app
            - /app/node_modules
        networks:
            - ecommerce-network
        depends_on:
            - users-microservice
            - auth-microservice
            - products-microservice
            - orders-microservice

    auth-microservice:
        container_name: auth-microservice
        restart: always
        build:
            context: ./auth-microservice
            dockerfile: Dockerfile
        volumes:
            - ./auth-microservice:/app
            - /app/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy
            users-microservice:
                condition: service_started

    users-microservice:
        container_name: users-microservice
        build:
            context: ./users-microservice
            dockerfile: Dockerfile
        volumes:
            - ./users-microservice:/app
            - /app/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

    products-microservice:
        container_name: products-microservice
        build:
            context: ./products-microservice
            dockerfile: Dockerfile
        volumes:
            - ./products-microservice:/app
            - /app/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

    orders-microservice:
        container_name: orders-microservice
        build:
            context: ./orders-microservice
            dockerfile: Dockerfile
        volumes:
            - ./orders-microservice:/app
            - /app/node_modules
        networks:
            - ecommerce-network
        depends_on:
            postgres:
                condition: service_healthy

networks:
    ecommerce-network:
        driver: bridge

volumes:
    postgres_data:
