INSERT INTO products (name, description, price, stock, "isActive", "createdAt", "updatedAt")
VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI and silent clicks.', 24.99, 120, true, NOW(), NOW()),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard with blue switches.', 79.90, 75, true, NOW(), NOW()),
('Bluetooth Headphones', 'Over-ear headphones with noise cancellation and 20h battery.', 59.50, 60, true, NOW(), NOW()),
('USB-C Charger', 'Fast charging USB-C wall charger, 30W output.', 18.99, 200, true, NOW(), NOW()),
('Smart LED Bulb', 'WiFi-enabled smart bulb, compatible with Alexa and Google Home.', 12.49, 150, true, NOW(), NOW()),
('Fitness Tracker', 'Waterproof fitness tracker with heart rate monitor.', 34.99, 90, true, NOW(), NOW()),
('Portable SSD 1TB', 'High-speed portable SSD with USB 3.2 support.', 109.00, 40, true, NOW(), NOW()),
('Gaming Chair', 'Ergonomic gaming chair with lumbar support and adjustable height.', 189.99, 25, true, NOW(), NOW()),
('4K Monitor', '27-inch 4K UHD monitor with HDR and slim bezels.', 299.99, 30, true, NOW(), NOW()),
('Laptop Stand', 'Aluminum adjustable laptop stand for desks.', 29.99, 110, true, NOW(), NOW()),
('Wireless Earbuds', 'True wireless earbuds with charging case and touch controls.', 39.99, 140, true, NOW(), NOW()),
('Smart Watch', 'Touchscreen smart watch with fitness and notification features.', 69.99, 80, true, NOW(), NOW()),
('Action Camera', '4K waterproof action camera with wide-angle lens.', 89.99, 50, true, NOW(), NOW()),
('Electric Toothbrush', 'Rechargeable electric toothbrush with 5 cleaning modes.', 22.99, 130, true, NOW(), NOW()),
('Coffee Grinder', 'Stainless steel electric coffee grinder, 200W.', 27.50, 70, true, NOW(), NOW()),
('Air Purifier', 'HEPA filter air purifier for rooms up to 40m².', 99.99, 35, true, NOW(), NOW()),
('Robot Vacuum', 'Smart robot vacuum cleaner with app control.', 179.00, 20, true, NOW(), NOW()),
('Electric Kettle', '1.7L fast boiling electric kettle with auto shut-off.', 19.99, 100, true, NOW(), NOW()),
('Desk Lamp', 'LED desk lamp with adjustable brightness and USB charging port.', 16.99, 95, true, NOW(), NOW()),
('Smart Plug', 'WiFi smart plug, works with Alexa and Google Assistant.', 11.99, 160, true, NOW(), NOW()),
('Noise Cancelling Earplugs', 'Reusable silicone earplugs for sleeping and travel.', 8.99, 180, true, NOW(), NOW()),
('Portable Projector', 'Mini portable projector with HDMI and USB inputs.', 129.99, 22, true, NOW(), NOW()),
('Wireless Charger', 'Qi-certified fast wireless charging pad.', 21.99, 105, true, NOW(), NOW()),
('Smart Scale', 'Bluetooth smart scale with body composition analysis.', 32.99, 60, true, NOW(), NOW()),
('Electric Scooter', 'Foldable electric scooter with 25km range.', 349.00, 10, true, NOW(), NOW()),
('Backpack', 'Water-resistant laptop backpack with USB charging port.', 44.99, 85, true, NOW(), NOW()),
('Thermal Mug', 'Stainless steel thermal mug, keeps drinks hot for 8 hours.', 14.99, 150, true, NOW(), NOW()),
('Webcam', '1080p HD webcam with built-in microphone.', 34.99, 70, true, NOW(), NOW()),
('Bluetooth Speaker', 'Portable Bluetooth speaker with deep bass.', 27.99, 120, true, NOW(), NOW()),
('Tablet Stand', 'Adjustable tablet stand for desk and kitchen use.', 13.99, 90, true, NOW(), NOW()),
('Smart Thermostat', 'WiFi smart thermostat with mobile app control.', 79.99, 18, true, NOW(), NOW()),
('Wireless Presenter', 'Wireless presenter with laser pointer and USB receiver.', 17.99, 65, true, NOW(), NOW()),
('Power Bank 20000mAh', 'High-capacity power bank with fast charging.', 29.99, 75, true, NOW(), NOW()),
('Photo Printer', 'Compact photo printer for smartphones.', 99.00, 28, true, NOW(), NOW()),
('Bluetooth Tracker', 'Key and wallet Bluetooth tracker with app alerts.', 15.99, 130, true, NOW(), NOW()),
('Smart Lock', 'Fingerprint and keypad smart door lock.', 119.99, 12, true, NOW(), NOW()),
('Streaming Stick', '4K streaming stick with voice remote.', 49.99, 55, true, NOW(), NOW()),
('Wireless Router', 'Dual-band wireless router with parental controls.', 59.99, 40, true, NOW(), NOW()),
('Portable Blender', 'USB rechargeable portable blender for smoothies.', 24.99, 80, true, NOW(), NOW()),
('Laptop Cooling Pad', 'Silent laptop cooling pad with 3 fans.', 18.99, 100, true, NOW(), NOW()),
('Smart Doorbell', 'WiFi video doorbell with motion detection.', 69.99, 25, true, NOW(), NOW()),
('Fitness Mat', 'Non-slip yoga and fitness mat, 6mm thick.', 21.99, 140, true, NOW(), NOW()),
('Digital Photo Frame', '10-inch digital photo frame with WiFi.', 59.99, 30, true, NOW(), NOW()),
('USB Hub', '4-port USB 3.0 hub with individual switches.', 13.99, 110, true, NOW(), NOW()),
('Smart Light Strip', 'RGB LED smart light strip, 5 meters.', 25.99, 60, true, NOW(), NOW()),
('Electric Shaver', 'Rechargeable electric shaver with 3 heads.', 34.99, 50, true, NOW(), NOW()),
('Wireless Gaming Controller', 'Bluetooth gaming controller for PC and mobile.', 42.99, 45, true, NOW(), NOW()),
('Car Dash Cam', 'Full HD car dash camera with night vision.', 54.99, 35, true, NOW(), NOW()),
('Smart Water Bottle', 'Hydration tracking smart water bottle, 600ml.', 27.99, 70, true, NOW(), NOW()),
('Portable Air Pump', 'Electric portable air pump for tires and balls.', 32.99, 55, true, NOW(), NOW()),
('Wireless Security Camera', 'Outdoor wireless security camera with night vision.', 79.99, 20, true, NOW(), NOW());